VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
VIAL_INSECURE = yes
LTO_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes
RADIAL_CONTROLLER_ENABLE = yes
JOYSTICK_ENABLE = yes       # 游戏摇杆/映射按键
JOYSTICK_DRIVER = analog

VIALRGB_ENABLE = yes

RGB_MATRIX_CUSTOM_USER = yes  # 开启用户自定义特效支持